local state    = require("codereview.state")
local store    = require("codereview.notes.store")
local config   = require("codereview.config")
local exporter = require("codereview.review.exporter")

describe("review.exporter.generate()", function()
  before_each(function()
    state.reset()
    store.reset_cache()
    config.setup({})
  end)

  it("returns a string starting with '# Review '", function()
    local out = exporter.generate()
    assert.truthy(out:match("^# Review %d%d%d%d%-%d%d%-%d%d"))
  end)

  it("returns placeholder text when there are no notes", function()
    local out = exporter.generate()
    assert.truthy(out:find("_Write your notes here._", 1, true))
  end)

  it("does not include placeholder when notes exist", function()
    store.set("src/foo.lua", 5, 5, "const x = 1", "revisar esto", "new")
    local out = exporter.generate()
    assert.falsy(out:find("_Write your notes here._", 1, true))
  end)

  it("includes the filepath as inline code anchor", function()
    store.set("src/foo.lua", 5, 5, "", "some note", "new")
    local out = exporter.generate()
    assert.truthy(out:find("`src/foo.lua`", 1, true))
  end)

  it("marks old-side notes with '(deleted)' in filepath anchor", function()
    store.set("src/bar.lua", 10, 10, "", "deleted note", "old")
    local out = exporter.generate()
    assert.truthy(out:find("`src/bar.lua (deleted)`", 1, true))
  end)

  it("includes the note text in the output", function()
    store.set("a.lua", 1, 1, "", "this is important", "new")
    local out = exporter.generate()
    assert.truthy(out:find("this is important", 1, true))
  end)

  it("includes the code block when code is provided", function()
    store.set("a.lua", 7, 9, "local x = 1\nlocal y = 2", "check math", "new")
    local out = exporter.generate()
    assert.truthy(out:find("```text{7,9}", 1, true))
    assert.truthy(out:find("local x = 1", 1, true))
  end)

  it("includes all notes from all files", function()
    store.set("a.lua", 1, 1, "", "note a", "new")
    store.set("b.lua", 1, 1, "", "note b", "new")
    local out = exporter.generate()
    assert.truthy(out:find("`a.lua`", 1, true))
    assert.truthy(out:find("`b.lua`", 1, true))
    assert.truthy(out:find("note a", 1, true))
    assert.truthy(out:find("note b", 1, true))
  end)

  it("emits notes sorted by filepath then line", function()
    store.set("z.lua", 1, 1, "", "note z", "new")
    store.set("a.lua", 5, 5, "", "note a5", "new")
    store.set("a.lua", 2, 2, "", "note a2", "new")
    local out = exporter.generate()
    local pos_a2 = out:find("note a2", 1, true)
    local pos_a5 = out:find("note a5", 1, true)
    local pos_z  = out:find("note z",  1, true)
    assert.is_true(pos_a2 < pos_a5)
    assert.is_true(pos_a5 < pos_z)
  end)

  it("multiline note text appears line by line in output", function()
    store.set("a.lua", 1, 1, "", "line one\nline two\nline three", "new")
    local out = exporter.generate()
    assert.truthy(out:find("line one", 1, true))
    assert.truthy(out:find("line two", 1, true))
    assert.truthy(out:find("line three", 1, true))
  end)

  it("notes without text do not insert an empty paragraph", function()
    store.set("a.lua", 1, 1, "code", "", "new")
    local out = exporter.generate()
    -- should not have two blank lines in a row from an empty text block
    assert.falsy(out:find("\n\n\n", 1, true))
  end)
end)
