local state = require("codereview.state")
local store = require("codereview.notes.store")

describe("notes.store", function()
  before_each(function()
    state.reset()
    store.reset_cache()
  end)

  -- set() / get()

  it("set() creates a note and get() retrieves it", function()
    store.set("src/foo.lua", 10, 10, "const x = 1", "check this", "new")
    local note = store.get("src/foo.lua", 10, "new")
    assert.is_not_nil(note)
    assert.equals("src/foo.lua", note.filepath)
    assert.equals(10, note.line_start)
    assert.equals(10, note.line_end)
    assert.equals("const x = 1", note.code)
    assert.equals("check this", note.text)
    assert.equals("new", note.side)
  end)

  it("set() defaults side to 'new' when not provided", function()
    store.set("a.lua", 5, 5, "", "note text")
    local note = store.get("a.lua", 5, "new")
    assert.is_not_nil(note)
    assert.equals("new", note.side)
  end)

  it("set() defaults line_end to line_start when not provided", function()
    store.set("a.lua", 7, nil, "", "note")
    local note = store.get("a.lua", 7, "new")
    assert.equals(7, note.line_end)
  end)

  it("set() marks state as dirty", function()
    store.set("a.lua", 1, 1, "", "x")
    assert.is_true(state.get().notes_dirty)
  end)

  it("get() returns nil for non-existent note", function()
    assert.is_nil(store.get("missing.lua", 1, "new"))
  end)

  it("set() updates an existing note at the same line and side", function()
    store.set("a.lua", 5, 5, "old code", "old text", "new")
    store.set("a.lua", 5, 5, "new code", "new text", "new")
    local note = store.get("a.lua", 5, "new")
    assert.equals("new code", note.code)
    assert.equals("new text", note.text)
  end)

  it("old-side and new-side notes at the same line are independent", function()
    store.set("a.lua", 3, 3, "", "new note", "new")
    store.set("a.lua", 3, 3, "", "old note", "old")
    assert.equals("new note", store.get("a.lua", 3, "new").text)
    assert.equals("old note", store.get("a.lua", 3, "old").text)
  end)

  -- delete()

  it("delete() removes an existing note", function()
    store.set("a.lua", 10, 10, "", "to delete", "new")
    store.delete("a.lua", 10, "new")
    assert.is_nil(store.get("a.lua", 10, "new"))
  end)

  it("delete() marks state as dirty", function()
    store.set("a.lua", 1, 1, "", "x")
    state.mark_notes_clean()
    store.delete("a.lua", 1, "new")
    assert.is_true(state.get().notes_dirty)
  end)

  it("delete() on a non-existent note does not error", function()
    assert.has_no.errors(function()
      store.delete("nonexistent.lua", 99, "new")
    end)
  end)

  -- get_for_file()

  it("get_for_file() returns empty table when file has no notes", function()
    local notes = store.get_for_file("empty.lua")
    assert.same({}, notes)
  end)

  it("get_for_file() returns all notes for a file", function()
    store.set("b.lua", 1, 1, "", "first")
    store.set("b.lua", 2, 2, "", "second")
    local notes = store.get_for_file("b.lua")
    assert.equals(2, #notes)
  end)

  it("get_for_file() returns notes sorted by line_start ascending", function()
    store.set("b.lua", 5, 5, "", "later")
    store.set("b.lua", 1, 1, "", "earlier")
    store.set("b.lua", 3, 3, "", "middle")
    local notes = store.get_for_file("b.lua")
    assert.equals(1, notes[1].line_start)
    assert.equals(3, notes[2].line_start)
    assert.equals(5, notes[3].line_start)
  end)

  it("get_for_file() does not include notes from other files", function()
    store.set("a.lua", 1, 1, "", "note a")
    store.set("b.lua", 1, 1, "", "note b")
    local notes = store.get_for_file("a.lua")
    assert.equals(1, #notes)
    assert.equals("a.lua", notes[1].filepath)
  end)

  -- count_for_file()

  it("count_for_file() returns 0 when no notes", function()
    assert.equals(0, store.count_for_file("nofile.lua"))
  end)

  it("count_for_file() counts all notes for the file", function()
    store.set("c.lua", 1, 1, "", "n1")
    store.set("c.lua", 2, 2, "", "n2")
    store.set("c.lua", 3, 3, "", "n3", "old")
    assert.equals(3, store.count_for_file("c.lua"))
  end)

  -- has_any()

  it("has_any() returns false when state is empty", function()
    assert.is_false(store.has_any())
  end)

  it("has_any() returns true once a note is added", function()
    store.set("x.lua", 1, 1, "", "note")
    assert.is_true(store.has_any())
  end)

  it("has_any() returns false after all notes are deleted", function()
    store.set("x.lua", 1, 1, "", "note")
    store.delete("x.lua", 1, "new")
    assert.is_false(store.has_any())
  end)

  -- get_all()

  it("get_all() returns empty table when no notes", function()
    assert.same({}, store.get_all())
  end)

  it("get_all() returns notes from all files", function()
    store.set("a.lua", 1, 1, "", "note in a")
    store.set("b.lua", 1, 1, "", "note in b")
    local all = store.get_all()
    assert.equals(2, #all)
  end)

  it("get_all() sorts by filepath then line_start", function()
    store.set("z.lua", 1, 1, "", "z note")
    store.set("a.lua", 5, 5, "", "a note 5")
    store.set("a.lua", 2, 2, "", "a note 2")
    local all = store.get_all()
    assert.equals("a.lua", all[1].filepath)
    assert.equals(2, all[1].line_start)
    assert.equals("a.lua", all[2].filepath)
    assert.equals(5, all[2].line_start)
    assert.equals("z.lua", all[3].filepath)
  end)

  -- reset_cache()

  it("reset_cache() forces re-sort on next get_for_file()", function()
    store.set("d.lua", 3, 3, "", "third")
    store.set("d.lua", 1, 1, "", "first")
    -- warm the cache
    store.get_for_file("d.lua")
    -- add a note that should appear at the front
    store.set("d.lua", 2, 2, "", "second")
    -- cache is invalidated automatically by set(), but reset_cache() must also work
    store.reset_cache()
    local notes = store.get_for_file("d.lua")
    assert.equals(3, #notes)
    assert.equals(1, notes[1].line_start)
  end)
end)
