local M = {}
local state = require("codereview.state")
local store = require("codereview.notes.store")
local config = require("codereview.config")

-- Generate the markdown review content
function M.generate()
  local date = os.date("%Y-%m-%d")
  local lines = {}

  table.insert(lines, "# Code Review — " .. date)
  table.insert(lines, "")
  table.insert(lines, "## Summary")
  table.insert(lines, "_Write your summary here._")
  table.insert(lines, "")
  table.insert(lines, "---")
  table.insert(lines, "")

  local all_notes = store.get_all()

  if #all_notes == 0 then
    table.insert(lines, "_No notes added._")
    table.insert(lines, "")
  else
    local current_file = nil

    for _, note in ipairs(all_notes) do
      if note.filepath ~= current_file then
        current_file = note.filepath
        table.insert(lines, "## `" .. current_file .. "`")
        table.insert(lines, "")
      end

      if note.line_start == note.line_end then
        table.insert(lines, "### Line " .. note.line_start)
      else
        table.insert(lines, "### Lines " .. note.line_start .. "–" .. note.line_end)
      end
      table.insert(lines, "")

      if note.code and note.code ~= "" then
        local ext = note.filepath:match("%.([^%.]+)$") or ""
        table.insert(lines, "```" .. ext)
        for code_line in (note.code .. "\n"):gmatch("([^\n]*)\n") do
          table.insert(lines, code_line)
        end
        table.insert(lines, "```")
        table.insert(lines, "")
      end

      for text_line in (note.text .. "\n"):gmatch("([^\n]*)\n") do
        table.insert(lines, "> " .. text_line)
      end
      table.insert(lines, "")
      table.insert(lines, "---")
      table.insert(lines, "")
    end
  end

  table.insert(lines, "_Generated by codereview_")

  return table.concat(lines, "\n")
end

-- Save to a file
function M.save(filepath)
  local content = M.generate()
  local f = io.open(filepath, "w")
  if not f then
    vim.notify("Error: could not write to " .. filepath, vim.log.levels.ERROR)
    return false
  end
  f:write(content)
  f:close()
  state.get().notes_dirty = false
  return true
end

-- Save directly to auto-generated path (no prompt)
function M.save_direct()
  local s = state.get()
  local cfg = config.options
  local default_name = os.date(cfg.review.default_filename)
  local save_dir = cfg.review.path or s.root or vim.fn.getcwd()
  local full_path = save_dir .. "/" .. default_name
  if M.save(full_path) then
    vim.notify("Review saved to " .. full_path, vim.log.levels.INFO)
  end
end

-- Save with vim.ui.input prompt
function M.save_with_prompt()
  local s = state.get()
  local cfg = config.options

  local default_name = os.date(cfg.review.default_filename)
  local save_dir = cfg.review.path or s.root or vim.fn.getcwd()

  vim.ui.input({
    prompt = "Save review as: ",
    default = default_name,
  }, function(filename)
    if not filename or filename == "" then return end

    if filename:sub(1, 1) == "/" then
      vim.notify(
        "codereview: absolute paths not allowed here — set review.path in your config instead",
        vim.log.levels.ERROR
      )
      return
    end

    local full_path = save_dir .. "/" .. filename

    if vim.fn.filereadable(full_path) == 1 then
      vim.ui.input({
        prompt = full_path .. " already exists. Overwrite? (y/N): ",
        default = "N",
      }, function(answer)
        if answer and answer:lower() == "y" then
          if M.save(full_path) then
            vim.notify("Review saved to " .. full_path, vim.log.levels.INFO)
          end
        else
          vim.notify("Save cancelled", vim.log.levels.INFO)
        end
      end)
    else
      if M.save(full_path) then
        vim.notify("Review saved to " .. full_path, vim.log.levels.INFO)
      end
    end
  end)
end

return M
